**This file contains** hiring statics for a firm such as **experience of candidate, his written test score and personal interview score.** Based on these 3 factors, HR will decide the salary. Given this data, you need to **build a machine learning model for HR department that can help them decide salaries for future candidates.** Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

Answer

1.   53713.86
2.   93747.79

In [15]:
import pandas as pd
import numpy as np
from sklearn import linear_model
!pip install word2number
from word2number import w2n

In [16]:
df = pd.read_csv('/content/hiring(multiple linear reg).csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [17]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [18]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [21]:
mean_score=df['test_score(out of 10)'].mean()
mean_score_int = int(mean_score)
mean_score_int

7

In [23]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mean_score_int)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [25]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

#OR(we can train our model in this way also by dropping the dependent variable i.e salary($))

In [26]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('salary($)',axis='columns'),df['salary($)'])

LinearRegression()

In [28]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [29]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

# Let's see how did we get these two answers

In [30]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [31]:
reg.intercept_

14992.65144669314

In [32]:
#y=m1x1+m2x2+m3x3+c
2922.26901502*2 + 2221.30909959*9 + 2147.48256637*6 + 14992.65144669314

53713.86677126314

In [33]:
#y=m1x1+m2x2+m3x3+c
2922.26901502*12 + 2221.30909959*10 + 2147.48256637*10 + 14992.65144669314

93747.79628653315