#Naive Bayes: Survival Prediction from titanic crash

In [20]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv('/content/titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [22]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [23]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [24]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [25]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [26]:
inputs.Age[:20]

0     22.0
1     38.0
2     26.0
3     35.0
4     35.0
5      NaN
6     54.0
7      2.0
8     27.0
9     14.0
10     4.0
11    58.0
12    20.0
13    39.0
14    14.0
15    55.0
16     2.0
17     NaN
18    31.0
19     NaN
Name: Age, dtype: float64

In [27]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean()).astype(int)
inputs.head(10)

Pclass     Sex  Age     Fare
0       3    male   22   7.2500
1       1  female   38  71.2833
2       3  female   26   7.9250
3       1  female   35  53.1000
4       3    male   35   8.0500
5       3    male   29   8.4583
6       1    male   54  51.8625
7       3    male    2  21.0750
8       3  female   27  11.1333
9       2  female   14  30.0708

In [28]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(10)

Pclass     Sex  Age     Fare  female  male
0       3    male   22   7.2500       0     1
1       1  female   38  71.2833       1     0
2       3  female   26   7.9250       1     0
3       1  female   35  53.1000       1     0
4       3    male   35   8.0500       0     1
5       3    male   29   8.4583       0     1
6       1    male   54  51.8625       0     1
7       3    male    2  21.0750       0     1
8       3  female   27  11.1333       1     0
9       2  female   14  30.0708       1     0

**Dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female**

In [30]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(10)

Pclass  Age     Fare  female
0       3   22   7.2500       0
1       1   38  71.2833       1
2       3   26   7.9250       1
3       1   35  53.1000       1
4       3   35   8.0500       0
5       3   29   8.4583       0
6       1   54  51.8625       0
7       3    2  21.0750       0
8       3   27  11.1333       1
9       2   14  30.0708       1

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=0.2)

In [40]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [41]:
model.fit(x_train,y_train)

GaussianNB()

In [42]:
model.score(x_test,y_test)

0.8156424581005587

In [43]:
x_test[0:10]

Pclass  Age      Fare  female
671       1   31   52.0000       0
94        3   59    7.2500       0
552       3   29    7.8292       0
327       2   36   13.0000       1
708       1   22  151.5500       1
601       3   29    7.8958       0
349       3   42    8.6625       0
413       2   29    0.0000       0
402       3   21    9.8250       1
384       3   29    7.8958       0

In [44]:
y_test[0:10]

671    0
94     0
552    0
327    1
708    1
601    0
349    0
413    0
402    0
384    0
Name: Survived, dtype: int64

In [46]:
model.predict(x_test)

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1])

In [48]:
model.predict_proba(x_test[:10])

array([[6.52860709e-01, 3.47139291e-01],
       [9.43026075e-01, 5.69739253e-02],
       [9.60745913e-01, 3.92540874e-02],
       [2.51550357e-01, 7.48449643e-01],
       [1.35024665e-04, 9.99864975e-01],
       [9.60751855e-01, 3.92481451e-02],
       [9.61401297e-01, 3.85987033e-02],
       [9.16655992e-01, 8.33440076e-02],
       [3.72193524e-01, 6.27806476e-01],
       [9.60751855e-01, 3.92481451e-02]])

**Here above we can see that first column is depicting "survived" and second column is depicting "NOT survived"**

**Just match predict_proba column values with the above model.predict values like first is 0 i.e NOT survived then in second column we can see that probability is less than 5 therefore second column is showing not survived**

**Now Calculate the score using cross validation**

In [54]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x_train, y_train, cv=5)

array([0.75524476, 0.72727273, 0.84507042, 0.73239437, 0.77464789])